import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#050B14',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.05)',
    backgroundColor: 'rgba(5, 11, 20, 0.95)',
  },
  backBtn: {
    marginRight: 12,
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerInfo: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  avatarMini: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#00A8FF20',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#00A8FF40',
  },
  avatarTextMini: {
    color: '#00A8FF',
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  headerTitle: {
    color: '#FFF',
    fontSize: 15,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  onlineStatus: {
    color: '#10b981',
    fontSize: 10,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  meetingHeaderBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(0, 168, 255, 0.12)',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(0, 168, 255, 0.3)',
  },
  meetingHeaderBtnText: {
    color: '#00A8FF',
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  chatArea: {
    flex: 1,
  },
  chatContent: {
    padding: 20,
    gap: 16,
  },
  msgRow: {
    flexDirection: 'row',
    width: '100%',
  },
  msgRowSelf: {
    justifyContent: 'flex-end',
  },
  msgRowOther: {
    justifyContent: 'flex-start',
  },
  bubble: {
    maxWidth: '80%',
    padding: 12,
    borderRadius: 16,
  },
  bubbleSelf: {
    backgroundColor: '#00A8FF',
    borderTopRightRadius: 4,
  },
  bubbleOther: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderTopLeftRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
  },
  msgText: {
    color: '#FFF',
    fontSize: 14,
    fontFamily: 'PlusJakartaSans-Medium',
    lineHeight: 20,
  },
  msgTime: {
    color: 'rgba(255, 255, 255, 0.5)',
    fontSize: 9,
    marginTop: 4,
    alignSelf: 'flex-end',
    fontFamily: 'PlusJakartaSans-Regular',
  },
  // Media bubbles
  mediaBubble: {
    width: 240,
    borderRadius: 16,
    overflow: 'hidden',
    padding: 8,
  },
  mediaBubbleSelf: {
    backgroundColor: '#0B233D',
    borderTopRightRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(0, 168, 255, 0.3)',
  },
  mediaBubbleOther: {
    backgroundColor: '#0B1728',
    borderTopLeftRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  imagePreview: {
    width: '100%',
    height: 160,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  mediaCaptionText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontFamily: 'PlusJakartaSans-Medium',
    marginTop: 8,
    marginHorizontal: 4,
  },
  mediaTimeText: {
    color: 'rgba(255, 255, 255, 0.5)',
    fontSize: 9,
    marginTop: 6,
    marginRight: 4,
    alignSelf: 'flex-end',
    fontFamily: 'PlusJakartaSans-Regular',
  },
  // Video card
  videoCard: {
    position: 'relative',
    width: '100%',
    height: 150,
    borderRadius: 12,
    overflow: 'hidden',
  },
  videoThumbnail: {
    width: '100%',
    height: '100%',
  },
  videoPlaceholder: {
    backgroundColor: '#1E293B',
  },
  videoOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  playIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(0, 168, 255, 0.85)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
  },
  videoDurationBadge: {
    position: 'absolute',
    bottom: 8,
    right: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  videoDurationText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  videoDetailsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 8,
    marginHorizontal: 4,
  },
  videoFilename: {
    flex: 1,
    color: '#E2E8F0',
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  // Audio bubble
  audioBubble: {
    width: 250,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderRadius: 16,
    gap: 10,
  },
  audioBubbleSelf: {
    backgroundColor: '#0B233D',
    borderTopRightRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(0, 168, 255, 0.3)',
  },
  audioBubbleOther: {
    backgroundColor: '#0B1728',
    borderTopLeftRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  audioPlayBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F59E0B',
    alignItems: 'center',
    justifyContent: 'center',
  },
  audioPlayBtnActive: {
    backgroundColor: '#EF4444',
  },
  audioWaveContainer: {
    flex: 1,
  },
  waveformBars: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    height: 38,
  },
  waveBar: {
    width: 3,
    borderRadius: 2,
  },
  audioMetaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  audioDurationText: {
    color: '#94A3B8',
    fontSize: 10,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  audioSizeText: {
    color: '#64748B',
    fontSize: 9,
    fontFamily: 'PlusJakartaSans-Regular',
  },
  audioTimeText: {
    color: 'rgba(255, 255, 255, 0.5)',
    fontSize: 9,
    alignSelf: 'flex-end',
    fontFamily: 'PlusJakartaSans-Regular',
  },
  // Document bubble
  docBubble: {
    width: 250,
    padding: 12,
    borderRadius: 16,
    gap: 10,
  },
  docBubbleSelf: {
    backgroundColor: '#0B233D',
    borderTopRightRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(0, 168, 255, 0.3)',
  },
  docBubbleOther: {
    backgroundColor: '#0B1728',
    borderTopLeftRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  docTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  docIconBox: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: 'rgba(139, 92, 246, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.3)',
  },
  docInfo: {
    flex: 1,
  },
  docFileName: {
    color: '#FFFFFF',
    fontSize: 13,
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  docFileSize: {
    color: '#94A3B8',
    fontSize: 11,
    fontFamily: 'PlusJakartaSans-Regular',
    marginTop: 2,
  },
  docDownloadBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: 'rgba(0, 168, 255, 0.1)',
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(0, 168, 255, 0.25)',
  },
  docDownloadText: {
    color: '#00A8FF',
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  docTimeText: {
    color: 'rgba(255, 255, 255, 0.5)',
    fontSize: 9,
    alignSelf: 'flex-end',
    fontFamily: 'PlusJakartaSans-Regular',
  },
  // Meeting Invite Bubble
  meetingCardBubble: {
    width: 260,
    padding: 14,
    borderRadius: 16,
    backgroundColor: '#0B233D',
    borderWidth: 1,
    borderColor: 'rgba(0, 168, 255, 0.4)',
    gap: 12,
  },
  meetingCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  meetingCardIconCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(0, 168, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  meetingCardTitle: {
    color: '#FFFFFF',
    fontSize: 13,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  meetingCardCode: {
    color: '#38BDF8',
    fontSize: 11,
    fontFamily: 'PlusJakartaSans-Medium',
    marginTop: 2,
  },
  meetingJoinBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#00A8FF',
    paddingVertical: 10,
    borderRadius: 12,
  },
  meetingJoinBtnText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  meetingCardTime: {
    color: 'rgba(255, 255, 255, 0.5)',
    fontSize: 9,
    alignSelf: 'flex-end',
    fontFamily: 'PlusJakartaSans-Regular',
  },
  // Input row
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 10,
    backgroundColor: 'rgba(5, 11, 20, 0.95)',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.05)',
    gap: 10,
  },
  attachBtnOutside: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
  },
  inputWrapper: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  input: {
    flex: 1,
    color: '#FFF',
    fontFamily: 'PlusJakartaSans-Medium',
    fontSize: 14,
    maxHeight: 100,
    paddingTop: Platform.OS === 'ios' ? 8 : 4,
    paddingBottom: Platform.OS === 'ios' ? 8 : 4,
  },
  sendBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#00A8FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: -10,
  },
  // Attachment sheet
  attachSheet: {
    backgroundColor: '#0B1728',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.1)',
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 10,
  },
  attachSheetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  attachSheetTitle: {
    color: '#94A3B8',
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-SemiBold',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  attachSheetClose: {
    padding: 4,
  },
  attachGrid: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingBottom: 4,
  },
  attachOption: {
    alignItems: 'center',
    gap: 8,
  },
  attachOptionIconBox: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  attachOptionLabel: {
    color: '#E2E8F0',
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  // Picker modal
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    justifyContent: 'flex-end',
  },
  pickerModalContent: {
    backgroundColor: '#0B1728',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 18,
    maxHeight: '70%',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  pickerModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.08)',
  },
  pickerModalTitle: {
    color: '#FFFFFF',
    fontSize: 17,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  pickerModalClose: {
    padding: 6,
  },
  pickerItemsList: {
    marginTop: 12,
  },
  pickerItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.05)',
    gap: 12,
  },
  pickerItemThumbnail: {
    width: 48,
    height: 48,
    borderRadius: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  pickerItemIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pickerItemInfo: {
    flex: 1,
  },
  pickerItemTitle: {
    color: '#FFFFFF',
    fontSize: 14,
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  pickerItemSubtitle: {
    color: '#94A3B8',
    fontSize: 11,
    fontFamily: 'PlusJakartaSans-Regular',
    marginTop: 2,
  },
  pickerSendChip: {
    backgroundColor: '#00A8FF',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  pickerSendChipText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  // Fullscreen modals
  fullscreenModal: {
    flex: 1,
    backgroundColor: '#000000',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fullscreenCloseBtn: {
    position: 'absolute',
    right: 20,
    zIndex: 10,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fullscreenImage: {
    width: '100%',
    height: '80%',
  },
  videoPlayerBox: {
    width: '90%',
    height: 380,
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: '#0B1728',
    borderWidth: 1,
    borderColor: 'rgba(0, 168, 255, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  videoPlayerImage: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.65,
  },
  videoPlayerCenterBtn: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#00A8FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoPlayerBottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(5, 11, 20, 0.85)',
    padding: 16,
  },
  videoPlayerTitle: {
    color: '#FFFFFF',
    fontSize: 15,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  videoPlayerDuration: {
    color: '#94A3B8',
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-Medium',
    marginTop: 4,
  },
  // Meeting option modal
  meetingModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  meetingModalCard: {
    width: '100%',
    backgroundColor: '#0B1728',
    borderRadius: 24,
    padding: 24,
    borderWidth: 1,
    borderColor: 'rgba(0, 168, 255, 0.3)',
    gap: 14,
  },
  meetingModalHeader: {
    alignItems: 'center',
    marginBottom: 8,
  },
  meetingModalIcon: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: 'rgba(0, 168, 255, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(0, 168, 255, 0.3)',
  },
  meetingModalTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontFamily: 'PlusJakartaSans-Bold',
    textAlign: 'center',
  },
  meetingModalSubtitle: {
    color: '#94A3B8',
    fontSize: 13,
    fontFamily: 'PlusJakartaSans-Regular',
    marginTop: 4,
    textAlign: 'center',
  },
  meetingModalPrimaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#00A8FF',
    paddingVertical: 14,
    borderRadius: 14,
  },
  meetingModalPrimaryText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  meetingModalSecondaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: 'rgba(0, 168, 255, 0.1)',
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(0, 168, 255, 0.25)',
  },
  meetingModalSecondaryText: {
    color: '#00A8FF',
    fontSize: 14,
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  meetingModalCancelBtn: {
    paddingVertical: 10,
    alignItems: 'center',
  },
  meetingModalCancelText: {
    color: '#64748B',
    fontSize: 13,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  emptyChatContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 100,
    paddingHorizontal: 32,
  },
  emptyChatIconBox: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: 'rgba(0, 168, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(0, 168, 255, 0.25)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  emptyChatTitle: {
    fontSize: 18,
    fontFamily: 'PlusJakartaSans-Bold',
    color: '#FFFFFF',
    marginBottom: 8,
    textAlign: 'center',
  },
  emptyChatSub: {
    fontSize: 14,
    fontFamily: 'PlusJakartaSans-Regular',
    color: '#94A3B8',
    textAlign: 'center',
    lineHeight: 20,
    maxWidth: 280,
  },
  customAttachForm: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 24,
  },
  limitBadgeRow: {
    marginBottom: 12,
    alignItems: 'flex-start',
    paddingHorizontal: 20,
  },
  limitBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(0, 168, 255, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(0, 168, 255, 0.3)',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  limitBadgeText: {
    color: '#00A8FF',
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  chooseFileBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: 'rgba(0, 168, 255, 0.1)',
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: 'rgba(0, 168, 255, 0.4)',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  chooseFileBtnText: {
    color: '#00A8FF',
    fontSize: 13,
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  inputErrorBorder: {
    borderColor: '#EF4444',
  },
  errorAlertBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(239, 68, 68, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.35)',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginTop: 8,
  },
  errorAlertText: {
    color: '#EF4444',
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-Medium',
    flex: 1,
  },
  customAttachLabel: {
    fontSize: 13,
    fontFamily: 'PlusJakartaSans-SemiBold',
    color: '#94A3B8',
    marginBottom: 8,
  },
  customAttachInput: {
    backgroundColor: '#050B14',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 14,
    fontFamily: 'PlusJakartaSans-Medium',
    color: '#FFFFFF',
  },
  customAttachActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 20,
  },
  customAttachCancelBtn: {
    flex: 1,
    paddingVertical: 13,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  customAttachCancelText: {
    fontSize: 14,
    fontFamily: 'PlusJakartaSans-SemiBold',
    color: '#94A3B8',
  },
  customAttachSendBtn: {
    flex: 1,
    flexDirection: 'row',
    paddingVertical: 13,
    borderRadius: 12,
    backgroundColor: '#00A8FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  customAttachSendText: {
    fontSize: 14,
    fontFamily: 'PlusJakartaSans-Bold',
    color: '#FFFFFF',
  },
});
