export const meetingWaitingRoomStyles = {
  // Waiting Room Styles
  waitingRoomRoot: {
    flex: 1,
    backgroundColor: '#050B14',
    paddingHorizontal: 20,
  },
  waitingRoomHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  waitingRoomBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.3)',
    gap: 6,
  },
  waitingRoomBadgeText: {
    color: '#10b981',
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  waitingRoomHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  waitingRoomScrollView: {
    flex: 1,
    width: '100%',
  },
  waitingRoomScroll: {
    alignItems: 'center',
    paddingBottom: 20,
  },
  waitingHeroBox: {
    alignItems: 'center',
    marginTop: 36,
    marginBottom: 20,
    position: 'relative',
    width: '100%',
  },
  waitingFooter: {
    width: '100%',
    paddingTop: 12,
    backgroundColor: '#050B14',
  },
  waitingGlowCircle: {
    position: 'absolute',
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: 'rgba(0, 168, 255, 0.14)',
    top: -5,
  },
  waitingRadarIconBox: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#0B1728',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(0, 168, 255, 0.4)',
    marginBottom: 14,
  },
  waitingStatusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 168, 255, 0.12)',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(0, 168, 255, 0.25)',
    gap: 6,
    marginBottom: 10,
  },
  waitingPulsingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#00A8FF',
  },
  waitingStatusPillText: {
    color: '#00A8FF',
    fontSize: 11,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  waitingTitleText: {
    color: '#FFF',
    fontSize: 19,
    fontFamily: 'PlusJakartaSans-Bold',
    textAlign: 'center',
    marginBottom: 6,
    paddingHorizontal: 16,
  },
  waitingSubText: {
    color: '#94a3b8',
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 18,
    fontFamily: 'PlusJakartaSans-Medium',
    paddingHorizontal: 16,
  },
  waitingInfoCard: {
    width: '100%',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    padding: 14,
    marginBottom: 14,
  },
  waitingInfoCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  waitingInfoLabel: {
    color: '#64748b',
    fontSize: 10,
    letterSpacing: 1,
    fontFamily: 'PlusJakartaSans-Bold',
    marginBottom: 3,
  },
  waitingInfoTitle: {
    color: '#FFF',
    fontSize: 15,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  waitingCodeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 168, 255, 0.1)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(0, 168, 255, 0.25)',
    gap: 6,
  },
  waitingCodeText: {
    color: '#00A8FF',
    fontSize: 12,
    fontFamily: 'monospace',
  },
  waitingPreviewCard: {
    width: '100%',
    height: 170,
    backgroundColor: '#0B1728',
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: 'rgba(0, 168, 255, 0.25)',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  waitingCameraContainer: {
    width: '100%',
    height: '100%',
    position: 'relative',
  },
  waitingCameraVideo: {
    width: '100%',
    height: '100%',
  },
  waitingFlipCameraBtn: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: 'rgba(0,0,0,0.6)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  waitingAvatarBox: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  waitingAvatarCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  waitingAvatarText: {
    color: '#FFF',
    fontSize: 22,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  waitingDisplayName: {
    color: '#FFF',
    fontSize: 14,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  waitingRoleTag: {
    color: '#94a3b8',
    fontSize: 11,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  waitingSetupSection: {
    width: '100%',
    marginBottom: 18,
  },
  waitingSetupTitle: {
    color: '#64748b',
    fontSize: 10,
    letterSpacing: 1,
    fontFamily: 'PlusJakartaSans-Bold',
    marginBottom: 8,
  },
  waitingSetupButtonsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  waitingSetupBtn: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    paddingVertical: 12,
    paddingHorizontal: 6,
    alignItems: 'center',
    gap: 3,
  },
  waitingSetupBtnActive: {
    borderColor: 'rgba(0, 168, 255, 0.35)',
  },
  waitingSetupBtnMuted: {
    backgroundColor: 'rgba(239, 68, 68, 0.08)',
    borderColor: 'rgba(239, 68, 68, 0.25)',
  },
  waitingIconCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 2,
  },
  iconCircleMuted: {
    backgroundColor: 'rgba(239, 68, 68, 0.2)',
  },
  iconCircleMic: {
    backgroundColor: 'rgba(16, 185, 129, 0.2)',
  },
  iconCircleVideo: {
    backgroundColor: 'rgba(0, 168, 255, 0.2)',
  },
  iconCircleNeutral: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
  },
  waitingBtnLabel: {
    color: '#FFF',
    fontSize: 11,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  waitingBtnSub: {
    fontSize: 10,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  waitingFullLeaveBtn: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: 'rgba(239, 68, 68, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.3)',
    borderRadius: 16,
    height: 46,
  },
  waitingFullLeaveBtnText: {
    color: '#ef4444',
    fontSize: 13,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  admittedBanner: {
    position: 'absolute',
    left: 20,
    right: 20,
    backgroundColor: 'rgba(16, 185, 129, 0.92)',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    zIndex: 999,
    elevation: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.25)',
  },
  admittedDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#FFF',
  },
  admittedBannerText: {
    color: '#FFF',
    fontSize: 13,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  // Host Admission Top Floating Prompt Banner
  hostAdmissionBanner: {
    position: 'absolute',
    left: 16,
    right: 16,
    backgroundColor: '#0c1a2e',
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 999,
    elevation: 12,
    borderWidth: 1.5,
    borderColor: 'rgba(0, 168, 255, 0.4)',
    shadowColor: '#00A8FF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
  },
  admissionBannerLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginRight: 10,
  },
  admissionBellBox: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(0, 168, 255, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(0, 168, 255, 0.3)',
  },
  admissionMeta: {
    flex: 1,
  },
  admissionGuestName: {
    color: '#FFF',
    fontSize: 14,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  admissionSubtitle: {
    color: '#94a3b8',
    fontSize: 11,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  admissionActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  admissionDenyBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.3)',
  },
  admissionDenyText: {
    color: '#ef4444',
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  admissionAdmitBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: '#00A8FF',
  },
  admissionAdmitText: {
    color: '#FFF',
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-Bold',
  },

  // Waiting Room Section inside Participants Drawer
  waitingDrawerCard: {
    marginHorizontal: 16,
    marginBottom: 16,
    backgroundColor: 'rgba(0, 168, 255, 0.08)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(0, 168, 255, 0.25)',
    padding: 12,
  },
  waitingDrawerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  waitingDrawerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  waitingDrawerTitle: {
    color: '#00A8FF',
    fontSize: 13,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  admitAllBtn: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 8,
    backgroundColor: '#00A8FF',
  },
  admitAllBtnText: {
    color: '#FFF',
    fontSize: 11,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  waitingDrawerList: {
    gap: 8,
  },
  waitingDrawerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.6)',
    borderRadius: 12,
    padding: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
  },
  waitingDrawerAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(0, 168, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  waitingDrawerAvatarText: {
    color: '#00A8FF',
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  waitingDrawerInfo: {
    flex: 1,
    marginRight: 8,
  },
  waitingDrawerName: {
    color: '#FFF',
    fontSize: 13,
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  waitingDrawerStatus: {
    color: '#64748b',
    fontSize: 11,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  waitingDrawerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  drawerDenyBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.3)',
  },
  drawerAdmitBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 8,
    backgroundColor: '#00A8FF',
  },
  drawerAdmitText: {
    color: '#FFF',
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  iosBroadcastPicker: {
    position: 'absolute',
    width: 1,
    height: 1,
    opacity: 0,
    bottom: -100,
  },
  reconnectingBanner: {
    position: 'absolute',
    left: 20,
    right: 20,
    backgroundColor: 'rgba(234, 88, 12, 0.95)',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 9999,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  reconnectingText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
};
