import { Dimensions, StyleSheet } from 'react-native';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const meetingLayoutStyles = {
  container: { flex: 1, backgroundColor: '#050B14', alignItems: 'center', justifyContent: 'center' },
  reconnectingPill: {
    position: 'absolute',
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(11, 23, 40, 0.95)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(0, 168, 255, 0.4)',
    zIndex: 9999,
    elevation: 8,
  },
  reconnectingPillText: {
    color: '#FFF',
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  contentContainer: { flex: 1, width: '100%', backgroundColor: '#050B14' },
  pipVideoOnly: { backgroundColor: '#000', overflow: 'hidden', borderWidth: 0 },
  pipChromeHidden: {
    display: 'none',
    opacity: 0,
    height: 0,
    maxHeight: 0,
    overflow: 'hidden',
    pointerEvents: 'none',
  },
  fullScreenTapSurface: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 15,
    elevation: 5,
  },
  pipActionBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 12,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
    zIndex: 40,
    elevation: 12,
  },
  pipActionBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(15, 23, 42, 0.88)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.16)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pipActionBtnMuted: {
    backgroundColor: 'rgba(239, 68, 68, 0.92)',
    borderColor: 'rgba(239, 68, 68, 0.5)',
  },
  pipActionBtnEnd: {
    backgroundColor: '#EF4444',
    borderColor: '#F87171',
  },
  loadingOverlay: { flex: 1, backgroundColor: '#050B14', alignItems: 'center', justifyContent: 'center', gap: 15 },
  loadingText: { color: '#FFF', fontSize: 16, fontFamily: 'PlusJakartaSans-Bold' },
  subLoadingText: { color: '#64748b', fontSize: 12, fontFamily: 'PlusJakartaSans-Medium' },
  header: { position: 'absolute', top: 0, left: 0, right: 0, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 16, paddingBottom: 12, borderBottomWidth: 1, borderBottomColor: 'rgba(255, 255, 255, 0.06)', backgroundColor: '#050B14', zIndex: 30, elevation: 10 },
  headerLeft: { flexDirection: 'row', gap: 8 },
  headerIconBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: 'rgba(255, 255, 255, 0.08)', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(255, 255, 255, 0.1)' },
  headerCenter: { alignItems: 'center' },
  titleRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  meetingTitle: { color: '#FFF', fontSize: 13, fontFamily: 'PlusJakartaSans-Bold' },
  timerText: { color: '#94a3b8', fontSize: 10, fontFamily: 'monospace' },
  leaveBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: 'rgba(239, 68, 68, 0.2)', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, borderWidth: 1, borderColor: 'rgba(239, 68, 68, 0.35)' },
  leaveText: { color: '#ef4444', fontSize: 12, fontFamily: 'PlusJakartaSans-Bold' },
  gridContainer: { flex: 1, width: '100%', height: '100%', backgroundColor: '#050B14' },
  fullScreenGridContainer: { padding: 0, backgroundColor: '#050B14' },
  multiGridContainer: { padding: 10, backgroundColor: '#050B14' },
  gridScrollView: { flex: 1, width: '100%' },
  gridContentContainer: { flexGrow: 1, paddingVertical: 2 },
  gridContentCenter: { justifyContent: 'center' },
  grid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', alignItems: 'center', alignContent: 'center', backgroundColor: '#050B14', minHeight: '100%', width: '100%' },
  participantCard: { width: (SCREEN_WIDTH - 30) / 2, height: '48%', backgroundColor: '#0B1728', borderRadius: 20, overflow: 'hidden', borderWidth: 1, borderColor: 'rgba(255, 255, 255, 0.1)' },
  videoNamePill: {
    position: 'absolute',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(5, 11, 20, 0.72)',
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    maxWidth: '85%',
    zIndex: 2,
  },
  videoNameText: {
    color: '#FFFFFF',
    fontFamily: 'PlusJakartaSans-Bold',
    letterSpacing: -0.2,
  },
  fullScreenCard: { width: '100%', height: '100%', borderRadius: 0, borderWidth: 0, backgroundColor: '#050B14', overflow: 'hidden' },
  activeSpeakerCard: { borderColor: '#10b981', borderWidth: 2 },
  cardVideo: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1,
  },
  // Floating Presenter Card on Screen Share
  floatingPresenterCard: {
    position: 'absolute',
    right: 16,
    width: 110,
    height: 145,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: 'rgba(11, 23, 40, 0.92)',
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    zIndex: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
  },
  floatingPresenterCardCollapsed: {
    width: 'auto',
    height: 36,
    paddingHorizontal: 12,
    borderRadius: 18,
  },
  floatingPresenterTouchable: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  floatingPresenterMediaBox: {
    flex: 1,
    width: '100%',
    position: 'relative',
    backgroundColor: '#050B14',
    alignItems: 'center',
    justifyContent: 'center',
  },
  floatingPresenterVideo: {
    width: '100%',
    height: '100%',
  },
  floatingPresenterAvatarBox: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  floatingPresenterAvatarCircle: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: 'rgba(0, 168, 255, 0.2)',
    borderWidth: 1,
    borderColor: '#00A8FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarCircleSpeaking: {
    borderColor: '#10b981',
    borderWidth: 2,
  },
  floatingPresenterAvatarText: {
    color: '#FFF',
    fontSize: 16,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  floatingPresenterRoleBadge: {
    position: 'absolute',
    top: 6,
    left: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 4,
  },
  floatingPresenterHostBadge: {
    backgroundColor: 'rgba(0, 168, 255, 0.85)',
  },
  floatingPresenterRoleText: {
    color: '#FFF',
    fontSize: 8,
    fontFamily: 'PlusJakartaSans-Bold',
    letterSpacing: 0.5,
  },
  floatingPresenterMicBadge: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(5, 11, 20, 0.8)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  floatingPresenterNameBanner: {
    width: '100%',
    paddingVertical: 4,
    paddingHorizontal: 6,
    backgroundColor: 'rgba(5, 11, 20, 0.85)',
    alignItems: 'center',
  },
  floatingPresenterNameText: {
    color: '#FFF',
    fontSize: 10,
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  floatingPresenterCollapsedContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  floatingPresenterCollapsedName: {
    color: '#FFF',
    fontSize: 11,
    fontFamily: 'PlusJakartaSans-SemiBold',
    maxWidth: 100,
  },
  miniAvatar: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#00A8FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  miniAvatarSpeaking: {
    backgroundColor: '#10b981',
  },
  miniAvatarText: {
    color: '#FFF',
    fontSize: 10,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  gridScreenShareCard: {
    width: '100%',
    height: 200,
    marginBottom: 8,
    borderColor: '#00A8FF',
    borderWidth: 1.5,
  },
  gridScreenShareBadge: {
    position: 'absolute',
    bottom: 8,
    left: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(5, 11, 20, 0.85)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(0, 168, 255, 0.4)',
  },
  gridScreenShareText: {
    color: '#FFF',
    fontSize: 11,
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  gridScreenShareLocalPlaceholder: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 12,
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#070d18',
  },
  gridScreenShareIconBadge: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(0, 168, 255, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(0, 168, 255, 0.4)',
  },
  gridScreenShareLocalTitle: {
    color: '#FFFFFF',
    fontSize: 13,
    fontFamily: 'PlusJakartaSans-Bold',
    lineHeight: 18,
    textAlign: 'center',
    marginBottom: 3,
  },
  gridScreenShareLocalSubtitle: {
    color: '#94a3b8',
    fontSize: 10.5,
    fontFamily: 'PlusJakartaSans-Medium',
    lineHeight: 15,
    textAlign: 'center',
    marginBottom: 8,
    paddingBottom: 2,
  },
  gridScreenShareTapHint: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    paddingHorizontal: 10,
    paddingVertical: 3.5,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.14)',
  },
  gridScreenShareTapHintText: {
    color: '#38bdf8',
    fontSize: 10,
    fontFamily: 'PlusJakartaSans-SemiBold',
    lineHeight: 14,
    paddingBottom: 1,
  },
  cardOverlay: { ...StyleSheet.absoluteFillObject, paddingHorizontal: 14, justifyContent: 'space-between' },
  cardTopRow: {
    position: 'absolute',
    left: 14,
    right: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 50,
    elevation: 10,
  },
  leftBadgeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  badgeRow: { flexDirection: 'row', gap: 8, alignItems: 'center' },
  hostBadge: {
    backgroundColor: 'rgba(16, 185, 129, 0.25)',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.45)',
  },
  hostBadgeText: {
    color: '#10b981',
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  youBadge: {
    backgroundColor: 'rgba(0, 168, 255, 0.25)',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(0, 168, 255, 0.45)',
  },
  youBadgeText: {
    color: '#00A8FF',
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  screenShareBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(0, 168, 255, 0.25)', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 10, borderWidth: 1, borderColor: 'rgba(0, 168, 255, 0.4)' },
  screenShareBadgeText: { color: '#00A8FF', fontSize: 12, fontFamily: 'PlusJakartaSans-Bold' },
  participantScreenShareBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 168, 255, 0.25)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(0, 168, 255, 0.45)',
  },
  participantScreenShareBadgeText: {
    color: '#00A8FF',
    fontFamily: 'PlusJakartaSans-SemiBold',
    fontSize: 10.5,
  },
  screenShareStopBadgeBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ef4444',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    shadowColor: '#ef4444',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.35,
    shadowRadius: 4,
    elevation: 4,
  },
  presentationContainer: {
    flex: 1,
    minHeight: 0,
    width: '100%',
    height: '100%',
    backgroundColor: '#050B14',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  screenShareStageContainer: {
    flex: 1,
    minHeight: 0,
    width: '100%',
    height: '100%',
    backgroundColor: '#050B14',
    position: 'relative',
    overflow: 'hidden',
  },
  fullStageVideo: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    backgroundColor: '#050B14',
  },
  participantThumbnailStripWrapper: {
    width: '100%',
    flexGrow: 0,
    flexShrink: 0,
    backgroundColor: 'rgba(5, 11, 20, 0.95)',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.08)',
    paddingTop: 6,
  },
  participantThumbnailStrip: {
    paddingHorizontal: 10,
    gap: 8,
    alignItems: 'center',
  },
  stripParticipantCard: {
    width: 84,
    height: 96,
    borderRadius: 10,
    overflow: 'hidden',
  },
  screenShareStopBadgeBtnText: {
    color: '#FFF',
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  screenSharePresenterCard: {
    flex: 1,
    width: '100%',
    height: '100%',
    backgroundColor: '#050B14',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
  },
  screenSharePresenterGlow: {
    position: 'absolute',
    width: 320,
    height: 320,
    borderRadius: 160,
    backgroundColor: 'rgba(0, 168, 255, 0.08)',
    shadowColor: '#00A8FF',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 60,
  },
  screenSharePresenterIconWrapper: {
    width: 120,
    height: 120,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
    position: 'relative',
  },
  screenSharePresenterPulseRing2: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 1.5,
    borderColor: 'rgba(0, 168, 255, 0.15)',
  },
  screenSharePresenterPulseRing1: {
    position: 'absolute',
    width: 102,
    height: 102,
    borderRadius: 51,
    borderWidth: 1.5,
    borderColor: 'rgba(0, 168, 255, 0.3)',
  },
  screenSharePresenterIconCircle: {
    width: 84,
    height: 84,
    borderRadius: 42,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#00A8FF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.45,
    shadowRadius: 14,
    elevation: 8,
  },
  screenShareLiveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(16, 185, 129, 0.18)',
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.4)',
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 20,
    marginBottom: 16,
  },
  screenShareLiveDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#10b981',
    marginRight: 8,
  },
  screenShareLiveBadgeText: {
    color: '#10b981',
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-Bold',
    letterSpacing: 0.5,
  },
  screenSharePresenterTitle: {
    color: '#FFF',
    fontSize: 20,
    fontFamily: 'PlusJakartaSans-Bold',
    textAlign: 'center',
    marginBottom: 10,
  },
  screenSharePresenterDesc: {
    color: '#94a3b8',
    fontSize: 14,
    fontFamily: 'PlusJakartaSans-Regular',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 28,
    paddingHorizontal: 12,
  },
  screenSharePresenterStopBtn: {
    borderRadius: 24,
    overflow: 'hidden',
    shadowColor: '#ef4444',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 6,
  },
  screenSharePresenterStopBtnGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
    paddingVertical: 14,
  },
  screenSharePresenterStopBtnText: {
    color: '#FFF',
    fontSize: 15,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  screenShareLoadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#050B14',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  screenShareLoadingText: {
    color: '#94a3b8',
    fontSize: 14,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  floatingScreenShareBanner: {
    position: 'absolute',
    left: 16,
    right: 16,
    zIndex: 99,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(11, 23, 40, 0.94)',
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.4)',
    shadowColor: '#ef4444',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  floatingBannerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: 10,
  },
  pulseDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#ef4444',
    marginRight: 8,
  },
  floatingBannerText: {
    color: '#FFF',
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  floatingStopBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ef4444',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    shadowColor: '#ef4444',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.35,
    shadowRadius: 4,
    elevation: 4,
  },
  floatingStopBtnText: {
    color: '#FFF',
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  rightBadgeActions: { flexDirection: 'row', alignItems: 'center', gap: 10, marginLeft: 'auto' },
  actionIconBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(11, 23, 40, 0.75)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.2,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.35,
    shadowRadius: 4,
    elevation: 6,
  },
  cardBottomRow: {
    position: 'absolute',
    left: 14,
    right: 14,
    zIndex: 50,
    elevation: 10,
  },
  namePill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(11, 23, 40, 0.78)',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 6,
  },
  participantName: {
    color: '#FFF',
    fontSize: 13,
    flex: 1,
    marginRight: 8,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  waveContainer: { flexDirection: 'row', alignItems: 'flex-end', gap: 2, marginRight: 6 },
  waveBar: { width: 2, backgroundColor: '#10b981', borderRadius: 1 },
  avatarContainer: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  fullScreenAvatarContainer: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  avatarCircle: { width: 60, height: 60, borderRadius: 30, alignItems: 'center', justifyContent: 'center' },
  largeAvatarCircle: { width: 96, height: 96, borderRadius: 48, alignItems: 'center', justifyContent: 'center' },
  avatarText: { color: '#FFF', fontSize: 20, fontFamily: 'PlusJakartaSans-Bold' },
  largeAvatarText: { color: '#FFF', fontSize: 32, fontFamily: 'PlusJakartaSans-Bold' },
  largeAvatarNameRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginTop: 14 },
  largeAvatarName: { color: '#FFFFFF', fontSize: 18, fontFamily: 'PlusJakartaSans-Bold', letterSpacing: -0.2 },
  gridAvatarNameRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginTop: 10, paddingHorizontal: 8 },
  gridAvatarName: { color: '#FFFFFF', fontSize: 15, fontFamily: 'PlusJakartaSans-Bold', letterSpacing: -0.2 },
  roleSubtext: { color: '#94a3b8', fontSize: 9, marginTop: 8, fontFamily: 'PlusJakartaSans-Medium' },
  footer: { position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: '#050B14', borderTopWidth: 1, borderTopColor: 'rgba(255, 255, 255, 0.06)', zIndex: 30, elevation: 10 },
  controlsDock: { flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center', paddingTop: 10 },
  controlItem: { alignItems: 'center', gap: 6 },
  controlIconBox: { width: 48, height: 48, borderRadius: 16, backgroundColor: 'rgba(255, 255, 255, 0.08)', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(255, 255, 255, 0.1)' },
  controlIconBoxMuted: { backgroundColor: 'rgba(239, 68, 68, 0.1)' },
  controlLabel: { color: '#94a3b8', fontSize: 10, fontFamily: 'PlusJakartaSans-SemiBold' },
  badge: { position: 'absolute', top: -5, right: -5, backgroundColor: '#ef4444', borderRadius: 10, paddingHorizontal: 5, paddingVertical: 1 },
  badgeText: { color: '#FFF', fontSize: 9, fontFamily: 'PlusJakartaSans-Bold' },
  chatBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: '#EF4444',
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
    borderWidth: 1.5,
    borderColor: '#0B1728',
  },
  chatBadgeText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontFamily: 'PlusJakartaSans-Bold',
    includeFontPadding: false,
  },
  waitingContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 10 },
  waitingText: { color: '#94a3b8', fontSize: 14, fontFamily: 'PlusJakartaSans-Medium' },
};
