export const meetingModalStyles = {
  // Info Modal Styles
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'flex-end' },
  modalContent: { backgroundColor: '#0B1728', borderTopLeftRadius: 32, borderTopRightRadius: 32, paddingHorizontal: 24, borderWidth: 1, borderColor: 'rgba(255, 255, 255, 0.1)' },
  modalDragHandle: { width: 40, height: 4, backgroundColor: '#334155', borderRadius: 2, alignSelf: 'center', marginTop: 12, marginBottom: 20 },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 },
  modalTitle: { color: '#FFF', fontSize: 18, fontFamily: 'PlusJakartaSans-Bold' },
  modalBody: { gap: 20, marginBottom: 10 },
  infoRow: { gap: 6 },
  infoLabel: { color: '#94a3b8', fontSize: 12, fontFamily: 'PlusJakartaSans-Bold', textTransform: 'uppercase', letterSpacing: 1 },
  infoValue: { color: '#FFF', fontSize: 15, fontFamily: 'PlusJakartaSans-SemiBold' },
  linkSection: { gap: 10 },
  linkDisplayBox: { height: 56, backgroundColor: 'rgba(0,0,0,0.3)', borderRadius: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, borderWidth: 1, borderColor: 'rgba(0, 168, 255, 0.2)' },
  linkDisplayText: { color: '#00A8FF', fontSize: 14, fontFamily: 'monospace', flex: 1, marginRight: 12 },
  copyHint: { color: '#64748b', fontSize: 11, fontFamily: 'PlusJakartaSans-Medium', textAlign: 'center' },

  // Leave Modal Styles
  leaveModalTitle: { color: '#FFF', fontSize: 18, fontFamily: 'PlusJakartaSans-Bold', textAlign: 'center', marginBottom: 8 },
  leaveModalSub: { color: '#94a3b8', fontSize: 14, fontFamily: 'PlusJakartaSans-Medium', textAlign: 'center', marginBottom: 24 },
  leaveModalActions: { gap: 12 },
  confirmLeaveBtn: { backgroundColor: '#ef4444', height: 56, borderRadius: 16, alignItems: 'center', justifyContent: 'center', shadowColor: '#ef4444', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.2, shadowRadius: 8 },
  confirmLeaveText: { color: '#FFF', fontSize: 16, fontFamily: 'PlusJakartaSans-Bold' },
  cancelLeaveBtn: { height: 56, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  cancelLeaveText: { color: '#94a3b8', fontSize: 16, fontFamily: 'PlusJakartaSans-Bold' },

  switchCameraBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    marginLeft: 'auto',
  },

  // Invite Modal Styles
  inviteModalContent: {
    backgroundColor: '#0B1728',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    maxHeight: '85%',
  },
  modalSubtitle: {
    color: '#64748b',
    fontSize: 12,
    marginTop: 2,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  inviteSearchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 16,
    paddingHorizontal: 14,
    height: 48,
    marginBottom: 12,
  },
  inviteSearchInput: {
    flex: 1,
    color: '#FFF',
    fontSize: 13,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  quickInviteRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 168, 255, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(0, 168, 255, 0.25)',
    borderRadius: 14,
    padding: 12,
    marginBottom: 14,
  },
  quickInviteIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: 'rgba(0, 168, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickInviteTitle: {
    color: '#FFF',
    fontSize: 13,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  quickInviteSub: {
    color: '#00A8FF',
    fontSize: 11,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  inviteBtnBadge: {
    backgroundColor: '#00A8FF',
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 10,
  },
  inviteBtnText: {
    color: '#FFF',
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  sectionHeaderLabel: {
    color: '#64748b',
    fontSize: 10,
    fontFamily: 'PlusJakartaSans-Bold',
    letterSpacing: 1,
    marginBottom: 8,
  },
  loadingUsersBox: {
    paddingVertical: 30,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  loadingUsersText: {
    color: '#94a3b8',
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  emptyUsersBox: {
    paddingVertical: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyUsersText: {
    color: '#64748b',
    fontSize: 12,
    textAlign: 'center',
    fontFamily: 'PlusJakartaSans-Medium',
  },
  inviteUsersList: {
    maxHeight: 240,
    marginBottom: 14,
  },
  inviteUserItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderRadius: 14,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
  },
  inviteAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#1E293B',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(0, 168, 255, 0.3)',
  },
  inviteAvatarText: {
    color: '#00A8FF',
    fontSize: 13,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  inviteUserInfo: {
    flex: 1,
    marginLeft: 12,
  },
  inviteUserName: {
    color: '#FFF',
    fontSize: 13,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  inviteUserHandle: {
    color: '#94a3b8',
    fontSize: 11,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  inviteActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 168, 255, 0.15)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(0, 168, 255, 0.3)',
  },
  inviteActionButtonSuccess: {
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    borderColor: 'rgba(16, 185, 129, 0.3)',
  },
  inviteActionButtonText: {
    color: '#00A8FF',
    fontSize: 11,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  inviteActionButtonTextSuccess: {
    color: '#10b981',
    fontSize: 11,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  inviteFooterShare: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  inviteFooterLeft: {
    flex: 1,
    marginRight: 10,
  },
  inviteFooterTitle: {
    color: '#64748b',
    fontSize: 10,
    fontFamily: 'PlusJakartaSans-Bold',
    textTransform: 'uppercase',
  },
  inviteFooterCode: {
    color: '#00A8FF',
    fontSize: 12,
    fontFamily: 'monospace',
    marginTop: 2,
  },
  inviteShareBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#00A8FF',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
  },
  inviteShareBtnText: {
    color: '#FFF',
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  // Audio Modal Styles
  audioModalContent: {
    backgroundColor: '#0B1728',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  refreshIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  audioDeviceList: {
    gap: 10,
    marginVertical: 12,
  },
  audioDeviceItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.06)',
  },
  audioDeviceItemSelected: {
    backgroundColor: 'rgba(0, 168, 255, 0.08)',
    borderColor: '#00A8FF',
  },
  audioDeviceIconBox: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  audioDeviceIconBoxSelected: {
    backgroundColor: 'rgba(0, 168, 255, 0.2)',
  },
  audioDeviceInfo: {
    flex: 1,
  },
  audioDeviceName: {
    color: '#E2E8F0',
    fontSize: 15,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  audioDeviceNameSelected: {
    color: '#00A8FF',
  },
  audioDeviceDesc: {
    color: '#64748b',
    fontSize: 12,
    marginTop: 2,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  audioDeviceCheckContainer: {
    marginLeft: 10,
  },
  audioActiveCheckBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#00A8FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  audioUncheckedCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  audioTipFooter: {
    backgroundColor: 'rgba(0, 0, 0, 0.25)',
    borderRadius: 14,
    padding: 12,
    marginTop: 6,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
  },
  audioTipText: {
    color: '#64748b',
    fontSize: 11,
    textAlign: 'center',
    fontFamily: 'PlusJakartaSans-Medium',
    lineHeight: 16,
  },
};
