import { StyleSheet } from 'react-native';

export const meetingDrawerStyles = {
  // Drawer Styles
  drawer: { position: 'absolute', inset: 0, backgroundColor: '#091322', zIndex: 100, paddingHorizontal: 20 },
  dragHandleWrapper: { alignItems: 'center', paddingVertical: 12 },
  dragHandle: { width: 48, height: 4, backgroundColor: '#334155', borderRadius: 2 },
  drawerHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingBottom: 16, borderBottomWidth: 1, borderBottomColor: 'rgba(255, 255, 255, 0.1)' },
  drawerTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  drawerTitle: { color: '#FFF', fontSize: 18, fontFamily: 'PlusJakartaSans-ExtraBold' },
  closeBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: 'rgba(255, 255, 255, 0.05)', alignItems: 'center', justifyContent: 'center' },
  emptyChat: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  emptyChatText: { color: '#64748b', fontSize: 13, textAlign: 'center', fontFamily: 'PlusJakartaSans-Medium' },
  chatList: { flex: 1, marginTop: 10 },

  chatInputRow: { flexDirection: 'row', gap: 8, alignItems: 'center', marginTop: 10, backgroundColor: '#0B1728', padding: 8, borderRadius: 20, borderWidth: 1, borderColor: 'rgba(255, 255, 255, 0.05)' },
  attachBtn: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 2,
  },
  chatInput: { flex: 1, height: 48, color: '#FFF', paddingHorizontal: 10, fontSize: 14, fontFamily: 'PlusJakartaSans-Medium' },
  sendBtn: { width: 44, height: 44, borderRadius: 14, backgroundColor: '#00A8FF', alignItems: 'center', justifyContent: 'center' },

  attachSheet: {
    backgroundColor: '#0B1728',
    borderRadius: 18,
    padding: 14,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  attachSheetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  attachSheetTitle: {
    color: '#FFF',
    fontSize: 14,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  attachSheetClose: {
    padding: 4,
  },
  attachGrid: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  attachOption: {
    alignItems: 'center',
    gap: 6,
  },
  attachOptionIconBox: {
    width: 48,
    height: 48,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  attachOptionLabel: {
    color: '#94a3b8',
    fontSize: 11,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  uploadingProgressBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 168, 255, 0.12)',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(0, 168, 255, 0.3)',
  },
  uploadingProgressText: {
    color: '#00A8FF',
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  // Attachment creator modal
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    justifyContent: 'flex-end',
  },
  pickerModalContent: {
    backgroundColor: '#0B1728',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  pickerModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  pickerModalTitle: {
    color: '#FFF',
    fontSize: 18,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  pickerModalClose: {
    padding: 4,
  },
  customAttachForm: {
    gap: 10,
  },
  limitBadgeRow: {
    marginBottom: 12,
    alignItems: 'flex-start',
  },
  limitBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(0, 168, 255, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(0, 168, 255, 0.3)',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  limitBadgeText: {
    color: '#00A8FF',
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  chooseFileBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: 'rgba(0, 168, 255, 0.1)',
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: 'rgba(0, 168, 255, 0.4)',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 4,
  },
  chooseFileBtnText: {
    color: '#00A8FF',
    fontSize: 13,
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  inputErrorBorder: {
    borderColor: '#EF4444',
  },
  errorAlertBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(239, 68, 68, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.35)',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginTop: 4,
  },
  errorAlertText: {
    color: '#EF4444',
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-Medium',
    flex: 1,
  },
  customAttachLabel: {
    color: '#94a3b8',
    fontSize: 13,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  customAttachInput: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: '#FFF',
    fontSize: 14,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  customAttachActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
    marginTop: 16,
  },
  customAttachCancelBtn: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
  },
  customAttachCancelText: {
    color: '#94a3b8',
    fontSize: 14,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  customAttachSendBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: '#00A8FF',
  },
  customAttachSendText: {
    color: '#FFF',
    fontSize: 14,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  // Media bubbles in chat
  mediaBubble: {
    width: 220,
    borderRadius: 16,
    overflow: 'hidden',
    padding: 8,
  },
  mediaBubbleSelf: {
    backgroundColor: '#0B233D',
    borderTopRightRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(0, 168, 255, 0.3)',
  },
  mediaBubbleOther: {
    backgroundColor: '#1E293B',
    borderTopLeftRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  imagePreview: {
    width: '100%',
    height: 130,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  imagePlaceholder: {
    width: '100%',
    height: 100,
    borderRadius: 12,
    backgroundColor: 'rgba(0, 168, 255, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  mediaCaptionText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontFamily: 'PlusJakartaSans-Medium',
    marginTop: 8,
    marginHorizontal: 4,
  },
  videoCard: {
    position: 'relative',
    width: '100%',
    height: 120,
    borderRadius: 12,
    overflow: 'hidden',
  },
  videoThumbnail: {
    width: '100%',
    height: '100%',
  },
  videoPlaceholder: {
    backgroundColor: '#0F172A',
  },
  videoOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  playIconCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(0, 168, 255, 0.9)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoDurationBadge: {
    position: 'absolute',
    bottom: 6,
    right: 6,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  videoDurationText: {
    color: '#FFF',
    fontSize: 10,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  videoDetailsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 8,
    marginHorizontal: 4,
  },
  videoFilename: {
    flex: 1,
    color: '#E2E8F0',
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  audioBubble: {
    width: 220,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderRadius: 16,
    gap: 10,
  },
  audioBubbleSelf: {
    backgroundColor: '#0B233D',
    borderTopRightRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(0, 168, 255, 0.3)',
  },
  audioBubbleOther: {
    backgroundColor: '#1E293B',
    borderTopLeftRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  audioPlayBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#F59E0B',
    alignItems: 'center',
    justifyContent: 'center',
  },
  audioWaveContainer: {
    flex: 1,
  },
  audioTitleText: {
    color: '#FFF',
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  audioDurationText: {
    color: '#94a3b8',
    fontSize: 10,
    fontFamily: 'PlusJakartaSans-Medium',
    marginTop: 2,
  },
  docBubble: {
    width: 220,
    padding: 12,
    borderRadius: 16,
  },
  docBubbleSelf: {
    backgroundColor: '#0B233D',
    borderTopRightRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(0, 168, 255, 0.3)',
  },
  docBubbleOther: {
    backgroundColor: '#1E293B',
    borderTopLeftRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  docTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  docIconBox: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: 'rgba(139, 92, 246, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.3)',
  },
  docInfo: {
    flex: 1,
  },
  docFileName: {
    color: '#FFF',
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  docFileSize: {
    color: '#94a3b8',
    fontSize: 10,
    fontFamily: 'PlusJakartaSans-Medium',
    marginTop: 2,
  },

  hostActionRow: { flexDirection: 'row', gap: 10, marginTop: 16 },
  muteAllBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: 'rgba(239, 68, 68, 0.1)', paddingVertical: 12, borderRadius: 14, borderWidth: 1, borderColor: 'rgba(239, 68, 68, 0.2)' },
  muteAllText: { color: '#ef4444', fontSize: 13, fontFamily: 'PlusJakartaSans-Bold' },
  inviteOthersBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: 'rgba(0, 168, 255, 0.15)', paddingVertical: 12, borderRadius: 14, borderWidth: 1, borderColor: 'rgba(0, 168, 255, 0.3)' },
  inviteOthersText: { color: '#00A8FF', fontSize: 13, fontFamily: 'PlusJakartaSans-Bold' },

  partList: { flex: 1, marginTop: 20 },
  partItem: { flexDirection: 'row', alignItems: 'center', padding: 14, borderRadius: 18, marginBottom: 12 },
  partItemBg: { backgroundColor: 'rgba(255, 255, 255, 0.03)', borderWidth: 1, borderColor: 'rgba(255, 255, 255, 0.05)' },
  partAvatarContainer: { position: 'relative' },
  partAvatar: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#334155', alignItems: 'center', justifyContent: 'center' },
  partAvatarText: { color: '#FFF', fontSize: 14, fontFamily: 'PlusJakartaSans-Bold' },
  partInfo: { flex: 1, marginLeft: 14 },
  nameRow: { flexDirection: 'row', alignItems: 'center' },
  partName: { color: '#FFF', fontSize: 14, fontFamily: 'PlusJakartaSans-Bold' },
  meBadge: { backgroundColor: 'rgba(0, 168, 255, 0.2)', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6, marginLeft: 8 },
  meBadgeText: { color: '#38bdf8', fontSize: 9, fontFamily: 'PlusJakartaSans-Bold' },
  partRole: { color: '#64748b', fontSize: 11, marginTop: 2, fontFamily: 'PlusJakartaSans-Medium' },
  partIcons: { flexDirection: 'row', alignItems: 'center' },
  partRemoveBtn: {
    padding: 6,
    borderRadius: 6,
    backgroundColor: 'rgba(239, 68, 68, 0.12)',
    marginRight: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },

  msgRow: { marginBottom: 20, alignItems: 'flex-start' },
  msgRowUser: { marginBottom: 20, alignItems: 'flex-end' },
  msgHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 6 },
  msgName: { fontSize: 12, fontFamily: 'PlusJakartaSans-Bold' },
  msgTime: { color: '#475569', fontSize: 10, marginLeft: 8, fontFamily: 'PlusJakartaSans-Medium' },
  msgBubble: { backgroundColor: 'rgba(255, 255, 255, 0.08)', padding: 14, borderRadius: 20, borderTopLeftRadius: 4, maxWidth: '85%', borderWidth: 1, borderColor: 'rgba(255, 255, 255, 0.05)' },
  msgBubbleUser: { padding: 14, borderRadius: 20, borderTopRightRadius: 4, maxWidth: '85%', shadowColor: '#00A8FF', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.2, shadowRadius: 8 },
  msgText: { color: '#FFF', fontSize: 13, lineHeight: 18, fontFamily: 'PlusJakartaSans-Medium' },
};
